name: Run Binary File

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # 允许手动触发
  repository_dispatch: # 允许webhook触发
    types: [run_binary_webhook]

jobs:
  run-binary:
    runs-on: windows-latest # 使用Windows运行环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup environment
        run: |
          echo "正在准备执行环境..."
          if (Test-Path .env) {
            Get-Content .env | ForEach-Object {
              if (-not [string]::IsNullOrWhiteSpace($_)) {
                $name, $value = $_.split('=', 2)
                echo "$name=$value" >> $env:GITHUB_ENV
              }
            }
          }

      - name: Run binary file
        env:
          # 从GitHub仓库设置中获取环境变量
          DATABASE_URL: ${{ env.DATABASE_URL }}
          DOMAIN: ${{ env.DOMAIN }}
          TEMP_MAIL: ${{ env.TEMP_MAIL }}
          TEMP_MAIL_EPIN: ${{ env.TEMP_MAIL_EPIN }}
          TEMP_MAIL_EXT: ${{ env.TEMP_MAIL_EXT }}
          BROWSER_USER_AGENT: ${{ env.BROWSER_USER_AGENT }}
          BROWSER_HEADLESS: ${{ env.BROWSER_HEADLESS }}
        run: |
          echo "开始执行二进制文件..."
          echo "DATABASE_URL: $DATABASE_URL"
          echo "DOMAIN: $DOMAIN"
          echo "TEMP_MAIL: $TEMP_MAIL"
          echo "TEMP_MAIL_EPIN: $TEMP_MAIL_EPIN"
          echo "TEMP_MAIL_EXT: $TEMP_MAIL_EXT"
          echo "BROWSER_USER_AGENT: $BROWSER_USER_AGENT"
          echo "BROWSER_HEADLESS: $BROWSER_HEADLESS"    
          .\cursorWork.exe
