name: Run Binary File

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # 允许手动触发
  repository_dispatch: # 允许webhook触发
    types: [run_binary_webhook]

jobs:
  run-binary:
    runs-on: windows-latest # 使用Windows运行环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run binary file
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DOMAIN: ${{ secrets.DOMAIN }}
          TEMP_MAIL: ${{ secrets.TEMP_MAIL }}
          TEMP_MAIL_EPIN: ${{ secrets.TEMP_MAIL_EPIN }}
          TEMP_MAIL_EXT: ${{ secrets.TEMP_MAIL_EXT }}
          BROWSER_USER_AGENT: ${{ secrets.BROWSER_USER_AGENT }}
          BROWSER_HEADLESS: ${{ secrets.BROWSER_HEADLESS }}
        run: |
          echo "开始执行二进制文件..."
          echo "DATABASE_URL: $DATABASE_URL"
          echo "DOMAIN: $DOMAIN"
          echo "TEMP_MAIL: $TEMP_MAIL"
          echo "TEMP_MAIL_EPIN: $TEMP_MAIL_EPIN"
          echo "TEMP_MAIL_EXT: $TEMP_MAIL_EXT"
          echo "BROWSER_USER_AGENT: $BROWSER_USER_AGENT"
          echo "BROWSER_HEADLESS: $BROWSER_HEADLESS"    
          .\cursorWork.exe
